var vlogs = [{
	   vlog_id: 1,
	   user_id: 1,
	   create_date: "2018-01-01",
	   log_date: "2018-01-01",
	   feeling: "good",
	   tag: "lunch",
	   video_link: "https://m.naver.com",
	   thumbnail_link: "https://m.naver.com",
	   video_ptime: 32,
	},
	{
	   vlog_id: 2,
	   user_id: 1,
	   create_date: "2018-01-03",
	   log_date: "2018-01-02",
	   feeling: "bad",
	   tag: "lunch",
	   video_link: "https://m.naver.com",
	   thumbnail_link: "https://m.naver.com",
	   video_ptime: 12,
	},
	{
	   vlog_id: 3,
	   user_id: 2,
	   create_date: "2018-01-03",
	   log_date: "2018-01-03",
	   feeling: "soso",
	   tag: "lunch",
	   video_link: "https://m.naver.com",
	   thumbnail_link: "https://m.naver.com",
	   video_ptime: 15,
	},
	{
	   vlog_id: 4,
	   user_id: 2,
	   create_date: "2018-01-04",
	   log_date: "2018-01-04",
	   feeling: "best",
	   tag: "lunch",
	   video_link: "https://m.naver.com",
	   thumbnail_link: "https://m.naver.com",
	   video_ptime: 745,
	},
	{
	   vlog_id: 5,
	   user_id: 2,
	   create_date: "2018-01-05",
	   log_date: "2018-01-05",
	   feeling: "worst",
	   tag: "WTF",
	   video_link: "https://m.naver.com",
	   thumbnail_link: "https://m.naver.com",
	   video_ptime: 4,
	},
	{
	   vlog_id: 6,
	   user_id: 3,
	   create_date: "2018-01-05",
	   log_date: "2018-01-04",
	   feeling: "worst",
	   tag: "sad",
	   video_link: "https://m.naver.com",
	   thumbnail_link: "https://m.naver.com",
	   video_ptime: 37,
	},
	{
	   vlog_id: 7,
	   user_id: 3,
	   create_date: "2018-01-06",
	   log_date: "2018-01-06",
	   feeling: "good",
	   tag: "lunch",
	   video_link: "https://m.naver.com",
	   thumbnail_link: "https://m.naver.com",
	   video_ptime: 28,
	},
	]

module.exports = vlogs;
